In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [2]:
X = np.load('Data/X_reference.npy')
y = np.load('Data/y_reference.npy')
class_num=0

FileNotFoundError: [Errno 2] No such file or directory: 'Data/X_reference.npy'

In [3]:
print(X)
print(y.shape)
print(y[2000],y[1999],y[2001],y[1998])
print(y)

[[0.35522984 0.30701063 0.34318911 ... 0.25676307 0.14707421 0.24007765]
 [0.23345617 0.32298293 0.24379364 ... 0.14759503 0.19269395 0.23601629]
 [0.20275288 0.28382089 0.30361074 ... 0.0975013  0.15016    0.19614416]
 ...
 [0.38041554 0.30664527 0.4541858  ... 0.40751397 0.29672716 0.35193382]
 [0.38186143 0.25524518 0.20992925 ... 0.43850126 0.39891844 0.46098642]
 [0.37358719 0.29174137 0.32681815 ... 0.68908333 0.39855016 0.38085587]]
(60000,)
1.0 0.0 1.0 0.0
[ 0.  0.  0. ... 29. 29. 29.]


In [4]:
#data generation for 1 bacteria
x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i*2000, (i+1)*2000):
        x = X[j]
        x_gen.append(x)
        yyy=[0.0]*4
        yyy[i]=1.0
        y_lbl.append(yyy+[class_num])
    class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
np.save('Data/X_datagen_for1', xx)
np.save('Data/y_datagen_for1', yy)

In [11]:
z=np.load('Data/y_datagen_for1.npy')
print(z)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 3.]
 [0. 0. 0. 1. 3.]
 [0. 0. 0. 1. 3.]]


In [5]:
#data generation for 2 bacteria


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
        for j in range(i+1,4):
            for _ in range(2000):
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                c1 = random.uniform(0.0,1)
                c2 = 1 - c1
                x = c1*X[first] + c2*X[second]
                x_gen.append(x)
                yyy=[0.0]*4
                yyy[i]=c1
                yyy[j]=c2
                y_lbl.append(yyy+[class_num])
            class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
np.save('Data/X_datagen_for2', xx)
np.save('Data/y_datagen_for2', yy)

In [12]:
z=np.load("Data/y_datagen_for2.npy")
print(z)

[[0.29143698 0.70856302 0.         0.         4.        ]
 [0.13816375 0.86183625 0.         0.         4.        ]
 [0.01490949 0.98509051 0.         0.         4.        ]
 ...
 [0.         0.         0.98302472 0.01697528 9.        ]
 [0.         0.         0.60932618 0.39067382 9.        ]
 [0.         0.         0.23261505 0.76738495 9.        ]]


In [7]:
#data generation for 3 bacteria


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
        for j in range(i+1,4):
            for k in range(j+1,4):
                for _ in range(2000):
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    c1=random.uniform(0.0,1)
                    c2=random.uniform(0.0,1-c1)
                    c3=1-c1-c2
                    conc=[c1,c2,c3]
                    random.shuffle(conc)
                    c1,c2,c3=conc[0],conc[1],conc[2]
                    x = c1*X[first] + c2*X[second] + c3*X[third]
                    x_gen.append(x)
                    yyy=[0.0]*4
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    y_lbl.append(yyy+[class_num])
                class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
np.save('Data/X_datagen_for3', xx)
np.save('Data/y_datagen_for3', yy)

In [8]:
z=np.load("Data/y_datagen_for3.npy")
print(z)

[[ 0.16343975  0.07350855  0.7630517   0.         10.        ]
 [ 0.45913473  0.47908205  0.06178323  0.         10.        ]
 [ 0.78954269  0.09894012  0.11151719  0.         10.        ]
 ...
 [ 0.          0.1812859   0.34300538  0.47570872 13.        ]
 [ 0.          0.28150357  0.40481166  0.31368477 13.        ]
 [ 0.          0.03585395  0.13333726  0.83080878 13.        ]]


In [9]:
#data generation for 4 bacteria


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
        for j in range(i+1,4):
            for k in range(j+1,4):
                for l in range(k+1,4):
                    for _ in range(2000):
                        first = np.random.randint(i*2000, (i+1)*2000)
                        second = np.random.randint(j*2000, (j+1)*2000)
                        third = np.random.randint(k*2000,(k+1)*2000)
                        fourth = np.random.randint(l*2000,(l+1)*2000)
                        c1=random.uniform(0.0,1)
                        c2=random.uniform(0.0,1-c1)
                        c3=random.uniform(0.0,1-c2-c1)
                        c4=1-c1-c2-c3
                        conc=[c1,c2,c3,c4]
                        random.shuffle(conc)
                        c1,c2,c3,c4=conc[0],conc[1],conc[2],conc[3]
                        x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]
                        x_gen.append(x)
                        yyy=[0.0]*4
                        yyy[i]=c1
                        yyy[j]=c2
                        yyy[k]=c3
                        yyy[l]=c4
                        y_lbl.append(yyy+[class_num])
                    class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
np.save('Data/X_datagen_for4', xx)
np.save('Data/y_datagen_for4', yy)

In [10]:
z=np.load('Data/y_datagen_for4.npy')
print(z)

[[1.18146808e-01 5.01714242e-01 1.65530320e-01 2.14608630e-01
  1.40000000e+01]
 [3.22773244e-01 4.88611839e-01 1.86086588e-01 2.52832911e-03
  1.40000000e+01]
 [4.90115120e-02 6.68367559e-03 9.56646251e-02 8.48640187e-01
  1.40000000e+01]
 ...
 [2.87367006e-02 6.10818189e-01 1.37926778e-01 2.22518333e-01
  1.40000000e+01]
 [3.91800828e-01 2.35784123e-01 1.75044093e-01 1.97370956e-01
  1.40000000e+01]
 [1.69031553e-02 6.94679307e-03 8.56958721e-02 8.90454179e-01
  1.40000000e+01]]


In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.model_selection import train_test_split


# Scaling
scaler = StandardScaler()
# X = scaler.fit_transform(X)

# X is the feature data, y is the target data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train an SVM model


# clf = SVC(kernel='rbf')
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

print(clf.score(X_test,y_test))

# print(X_test,X_test.shape)

y_pred = clf.predict(X_test)

# Confusion matrix
print("Confusion Matrix: \n", metrics.confusion_matrix(y_test, y_pred))

# Accuracy
print("Accuracy: {:.2f}%".format(metrics.accuracy_score(y_test, y_pred)*100))








KeyboardInterrupt: 