In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [186]:
X = np.load('Data/X_reference.npy')
y = np.load('Data/y_reference.npy')
class_num=0
num_each=2000

In [187]:
print(X)
print(y.shape)
print(y[2000],y[1999],y[2001],y[1998])
print(y)

[[0.35522984 0.30701063 0.34318911 ... 0.25676307 0.14707421 0.24007765]
 [0.23345617 0.32298293 0.24379364 ... 0.14759503 0.19269395 0.23601629]
 [0.20275288 0.28382089 0.30361074 ... 0.0975013  0.15016    0.19614416]
 ...
 [0.38041554 0.30664527 0.4541858  ... 0.40751397 0.29672716 0.35193382]
 [0.38186143 0.25524518 0.20992925 ... 0.43850126 0.39891844 0.46098642]
 [0.37358719 0.29174137 0.32681815 ... 0.68908333 0.39855016 0.38085587]]
(60000,)
1.0 0.0 1.0 0.0
[ 0.  0.  0. ... 29. 29. 29.]


In [188]:
#data generation for 1 bacteria and 1 foreign
x_gen = []
y_lbl = []
for i in range(4):
    #with_foreign
    for j in range(i*2000, (i+1)*2000):
        foreign = np.random.randint(8000, 16000)
        cf=random.uniform(0.0,1)
        c1=1-cf
        x = c1*X[j]+cf*X[foreign]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=c1
        yyy[4]=cf
        y_lbl.append(yyy+[class_num])
    class_num+=1
    #without_foreign
    for j in range(i*2000, (i+1)*2000):
        x = X[j]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=c1
        y_lbl.append(yyy+[class_num])
    class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for1_withforeign_class', yyc)
np.save('Data/X_datagen_for1_withforeign', xx)
np.save('Data/y_datagen_for1_withforeign', yy)

In [189]:
data1_1=np.load('Data/y_datagen_for1_withforeign_class.npy')
data1_2=np.load('Data/X_datagen_for1_withforeign.npy')
print(data1_1)

[0. 0. 0. ... 7. 7. 7.]


In [190]:
#data generation for 2 bacteria and 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        #with_foreign
        for _ in range(num_each):
            foreign = np.random.randint(8000, 16000)
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            cf=random.uniform(0.0,1)
            c1 = random.uniform(0.0,1-cf)
            c2 = 1 - c1 -cf
            conc=[c1,c2,cf]
            random.shuffle(conc)
            c1,c2,cf=conc[0],conc[1],conc[2]
            x = c1*X[first] + c2*X[second] +cf*X[foreign]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            yyy[4]=cf
            y_lbl.append(yyy+[class_num])
        class_num+=1
        #without_foreign
        for _ in range(num_each):
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            c1 = random.uniform(0.0,1)
            c2 = 1 - c1
            conc=[c1,c2]
            random.shuffle(conc)
            c1,c2=conc[0],conc[1]
            x = c1*X[first] + c2*X[second]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            y_lbl.append(yyy+[class_num])
        class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for2_withforeign_class', yyc)
np.save('Data/X_datagen_for2_withforeign', xx)
np.save('Data/y_datagen_for2_withforeign', yy)

In [191]:
data2_1=np.load("Data/y_datagen_for2_withforeign_class.npy")
data2_2=np.load('Data/X_datagen_for2_withforeign.npy')
print(data2_1)

[ 8.  8.  8. ... 19. 19. 19.]


In [192]:
#data generation for 3 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            #with_foreign
            for _ in range(num_each):
                foreign = np.random.randint(8000, 16000)
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                cf=random.uniform(0.0,1)
                c1=random.uniform(0.0,1-cf)
                c2=random.uniform(0.0,1-c1-cf)
                c3=1-c1-c2-cf
                conc=[c1,c2,c3,cf]
                random.shuffle(conc)
                c1,c2,c3,cf=conc[0],conc[1],conc[2],conc[3]
                x = c1*X[first] + c2*X[second] + c3*X[third]+cf*X[foreign]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                yyy[4]=cf
                y_lbl.append(yyy+[class_num])
            class_num+=1
            #without_foreign
            for _ in range(num_each):
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                c1=random.uniform(0.0,1)
                c2=random.uniform(0.0,1-c1)
                c3=1-c1-c2
                conc=[c1,c2,c3]
                random.shuffle(conc)
                c1,c2,c3=conc[0],conc[1],conc[2]
                x = c1*X[first] + c2*X[second] + c3*X[third]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                y_lbl.append(yyy+[class_num])
            class_num+=1

xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for3_withforeign_class', yyc)
np.save('Data/X_datagen_for3_withforeign', xx)
np.save('Data/y_datagen_for3_withforeign', yy)

In [193]:
data3_1=np.load("Data/y_datagen_for3_withforeign_class.npy")
data3_2=np.load('Data/X_datagen_for3_withforeign.npy')
print(data3_1)

[20. 20. 20. ... 27. 27. 27.]


In [194]:
#data generation for 4 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            for l in range(k+1,4):
                #with_foreign
                for _ in range(num_each):
                    foreign = np.random.randint(8000, 16000)
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    cf=random.uniform(0.0,1)
                    c1=random.uniform(0.0,1-cf)
                    c2=random.uniform(0.0,1-c1-cf)
                    c3=random.uniform(0.0,1-c2-c1-cf)
                    c4=1-c1-c2-c3-cf
                    conc=[c1,c2,c3,c4,cf]
                    random.shuffle(conc)
                    c1,c2,c3,c4,cf=conc[0],conc[1],conc[2],conc[3],conc[4]
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]+cf*X[foreign]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    yyy[4]=cf
                    y_lbl.append(yyy+[class_num])
                class_num+=1
                #without_foreign
                for _ in range(num_each):
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    c1=random.uniform(0.0,1)
                    c2=random.uniform(0.0,1-c1)
                    c3=random.uniform(0.0,1-c2-c1)
                    c4=1-c1-c2-c3
                    conc=[c1,c2,c3,c4]
                    random.shuffle(conc)
                    c1,c2,c3,c4=conc[0],conc[1],conc[2],conc[3]
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    y_lbl.append(yyy+[class_num])
                class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for4_withforeign_class', yyc)
np.save('Data/X_datagen_for4_withforeign', xx)
np.save('Data/y_datagen_for4_withforeign', yy)

In [195]:
data4_1=np.load('Data/y_datagen_for4_withforeign_class.npy')
data4_2=np.load('Data/X_datagen_for4_withforeign.npy')
print(data4_1)

[28. 28. 28. ... 29. 29. 29.]


In [199]:
XXfinal=np.vstack((data1_2,data2_2, data3_2,data4_2))
yyfinal = np.hstack((data1_1,data2_1, data3_1,data4_1))
print(XXfinal)
print(yyfinal)
np.save('Data/X_datagen_allcomb_foreign_class', XXfinal)
np.save('Data/y_datagen_allcomb_foreign_class', yyfinal)

[[0.29556986 0.28381637 0.30261862 ... 0.3050687  0.16794992 0.24918756]
 [0.39169162 0.38946491 0.33785144 ... 0.47199899 0.45171341 0.62970055]
 [0.21996199 0.26525475 0.31075499 ... 0.19474426 0.21922579 0.18761634]
 ...
 [0.23207348 0.16856434 0.26191739 ... 0.38763052 0.27080591 0.39754983]
 [0.21462793 0.27112808 0.18279617 ... 0.26344809 0.28957727 0.33867552]
 [0.24464102 0.23916119 0.30441345 ... 0.2497406  0.44087268 0.39621531]]
[ 0.  0.  0. ... 29. 29. 29.]


In [197]:
np.unique(yyfinal)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])