In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [37]:
X = np.load('Data/X_reference.npy')
y = np.load('Data/y_reference.npy')
class_num=0
num_each=2000

In [38]:
print(X)
print(y.shape)
print(y[2000],y[1999],y[2001],y[1998])
print(y)

yhot=[]

[[0.35522984 0.30701063 0.34318911 ... 0.25676307 0.14707421 0.24007765]
 [0.23345617 0.32298293 0.24379364 ... 0.14759503 0.19269395 0.23601629]
 [0.20275288 0.28382089 0.30361074 ... 0.0975013  0.15016    0.19614416]
 ...
 [0.38041554 0.30664527 0.4541858  ... 0.40751397 0.29672716 0.35193382]
 [0.38186143 0.25524518 0.20992925 ... 0.43850126 0.39891844 0.46098642]
 [0.37358719 0.29174137 0.32681815 ... 0.68908333 0.39855016 0.38085587]]
(60000,)
1.0 0.0 1.0 0.0
[ 0.  0.  0. ... 29. 29. 29.]


In [39]:
#data generation for 1 bacteria and 1 foreign
x_gen = []
y_lbl = []
for i in range(4):
    #with_foreign
    for j in range(i*2000, (i+1)*2000):
        foreign = np.random.randint(8000, 16000)
        cf=random.uniform(0.0,1)
        c1=1-cf
        x = c1*X[j]+cf*X[foreign]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=c1
        yyy[4]=cf
        yhotenc=[0.0]*5
        yhotenc[i]=1.0
        yhotenc[4]=1.0
        yhot.append(yhotenc)
        y_lbl.append(yyy+[class_num])
        
    class_num+=1
    #without_foreign
    for j in range(i*2000, (i+1)*2000):
        x = X[j]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=c1
        yhotenc=[0.0]*5
        yhotenc[i]=1.0
        yhot.append(yhotenc)
        y_lbl.append(yyy+[class_num])
    class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
print(yhot)
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for1_withforeign_class', yyc)
np.save('Data/X_datagen_for1_withforeign', xx)
np.save('Data/y_datagen_for1_withforeign', yy)

[[1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], 

In [40]:
data1_1=np.load('Data/y_datagen_for1_withforeign_class.npy')
data1_2=np.load('Data/X_datagen_for1_withforeign.npy')

print(data1_1)

[0. 0. 0. ... 7. 7. 7.]


In [41]:
#data generation for 2 bacteria and 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        #with_foreign
        for _ in range(num_each):
            foreign = np.random.randint(8000, 16000)
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            cf=random.uniform(0.0,1)
            c1 = random.uniform(0.0,1-cf)
            c2 = 1 - c1 -cf
            conc=[c1,c2,cf]
            random.shuffle(conc)
            c1,c2,cf=conc[0],conc[1],conc[2]
            x = c1*X[first] + c2*X[second] +cf*X[foreign]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            yyy[4]=cf
            yhotenc=[0.0]*5
            yhotenc[i]=1.0
            yhotenc[j]=1.0
            yhotenc[4]=1.0
            yhot.append(yhotenc)
            y_lbl.append(yyy+[class_num])
        class_num+=1
        #without_foreign
        for _ in range(num_each):
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            c1 = random.uniform(0.0,1)
            c2 = 1 - c1
            conc=[c1,c2]
            random.shuffle(conc)
            c1,c2=conc[0],conc[1]
            x = c1*X[first] + c2*X[second]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            yhotenc=[0.0]*5
            yhotenc[i]=1.0
            yhotenc[j]=1.0
            yhot.append(yhotenc)
            y_lbl.append(yyy+[class_num])
        class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]

np.save('Data/y_datagen_for2_withforeign_class', yyc)
np.save('Data/X_datagen_for2_withforeign', xx)
np.save('Data/y_datagen_for2_withforeign', yy)

In [42]:
data2_1=np.load("Data/y_datagen_for2_withforeign_class.npy")
data2_2=np.load('Data/X_datagen_for2_withforeign.npy')

print(data2_1)

[ 8.  8.  8. ... 19. 19. 19.]


In [43]:
#data generation for 3 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            #with_foreign
            for _ in range(num_each):
                foreign = np.random.randint(8000, 16000)
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                cf=random.uniform(0.0,1)
                c1=random.uniform(0.0,1-cf)
                c2=random.uniform(0.0,1-c1-cf)
                c3=1-c1-c2-cf
                conc=[c1,c2,c3,cf]
                random.shuffle(conc)
                c1,c2,c3,cf=conc[0],conc[1],conc[2],conc[3]
                x = c1*X[first] + c2*X[second] + c3*X[third]+cf*X[foreign]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                yyy[4]=cf
                yhotenc=[0.0]*5
                yhotenc[i]=1.0
                yhotenc[j]=1.0
                yhotenc[k]=1.0
                yhotenc[4]=1.0
                yhot.append(yhotenc)
                y_lbl.append(yyy+[class_num])
            class_num+=1
            #without_foreign
            for _ in range(num_each):
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                c1=random.uniform(0.0,1)
                c2=random.uniform(0.0,1-c1)
                c3=1-c1-c2
                conc=[c1,c2,c3]
                random.shuffle(conc)
                c1,c2,c3=conc[0],conc[1],conc[2]
                x = c1*X[first] + c2*X[second] + c3*X[third]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                yhotenc=[0.0]*5
                yhotenc[i]=1.0
                yhotenc[j]=1.0
                yhotenc[k]=1.0
                yhot.append(yhotenc)
                y_lbl.append(yyy+[class_num])
            class_num+=1

xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]

for i in yy:
    yyc+=[i[-1]]

np.save('Data/y_datagen_for3_withforeign_class', yyc)
np.save('Data/X_datagen_for3_withforeign', xx)
np.save('Data/y_datagen_for3_withforeign', yy)

In [44]:
data3_1=np.load("Data/y_datagen_for3_withforeign_class.npy")
data3_2=np.load('Data/X_datagen_for3_withforeign.npy')

print(data3_1)

[20. 20. 20. ... 27. 27. 27.]


In [45]:
#data generation for 4 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            for l in range(k+1,4):
                #with_foreign
                for _ in range(num_each):
                    foreign = np.random.randint(8000, 16000)
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    cf=random.uniform(0.0,1)
                    c1=random.uniform(0.0,1-cf)
                    c2=random.uniform(0.0,1-c1-cf)
                    c3=random.uniform(0.0,1-c2-c1-cf)
                    c4=1-c1-c2-c3-cf
                    conc=[c1,c2,c3,c4,cf]
                    random.shuffle(conc)
                    c1,c2,c3,c4,cf=conc[0],conc[1],conc[2],conc[3],conc[4]
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]+cf*X[foreign]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    yyy[4]=cf
                    yhotenc=[0.0]*5
                    yhotenc[i]=1.0
                    yhotenc[j]=1.0
                    yhotenc[k]=1.0
                    yhotenc[l]=1.0
                    yhotenc[4]=1.0
                    yhot.append(yhotenc)
                    y_lbl.append(yyy+[class_num])
                class_num+=1
                #without_foreign
                for _ in range(num_each):
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    c1=random.uniform(0.0,1)
                    c2=random.uniform(0.0,1-c1)
                    c3=random.uniform(0.0,1-c2-c1)
                    c4=1-c1-c2-c3
                    conc=[c1,c2,c3,c4]
                    random.shuffle(conc)
                    c1,c2,c3,c4=conc[0],conc[1],conc[2],conc[3]
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    yhotenc=[0.0]*5
                    yhotenc[i]=1.0
                    yhotenc[j]=1.0
                    yhotenc[k]=1.0
                    yhotenc[l]=1.0
                    yhot.append(yhotenc)
                    y_lbl.append(yyy+[class_num])
                class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]

np.save('Data/y_datagen_for4_withforeign_class', yyc)
np.save('Data/X_datagen_for4_withforeign', xx)
np.save('Data/y_datagen_for4_withforeign', yy)

In [46]:
data4_1=np.load('Data/y_datagen_for4_withforeign_class.npy')
data4_2=np.load('Data/X_datagen_for4_withforeign.npy')

print(data4_1_1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 ...
 [1 1 1 1 0]
 [1 1 1 1 0]
 [1 1 1 1 0]]


In [47]:
XXfinalclass=np.vstack((data1_2,data2_2, data3_2,data4_2))
yyfinalclass = np.hstack((data1_1,data2_1, data3_1,data4_1))
print(XXfinalclass)
print(yyfinalclass)

np.save('Data/X_datagen_allcomb_foreign_class', XXfinalclass)
np.save('Data/y_datagen_allcomb_foreign_class', yyfinalclass)


[[0.32864106 0.32255863 0.33210079 ... 0.20447888 0.22516276 0.26070804]
 [0.31218315 0.41214796 0.28068633 ... 0.29507242 0.25538008 0.32090288]
 [0.21563633 0.28872983 0.29345493 ... 0.14738522 0.19516345 0.2262104 ]
 ...
 [0.25663888 0.37213814 0.47791016 ... 0.26319535 0.23010556 0.5551193 ]
 [0.25662082 0.25908259 0.22128743 ... 0.16298952 0.24840819 0.16947846]
 [0.31349188 0.2574448  0.4282464  ... 0.47835303 0.40992902 0.55286394]]
[ 0.  0.  0. ... 29. 29. 29.]


In [51]:
print(yhot)
np.save("Data/y_datagen_allcomb_foreign_hotencoding",yhot)

z=np.load("Data/y_datagen_allcomb_foreign_hotencoding.npy")
print(z.shape)
print(z)

[[1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], 