In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [2]:
X = np.load('Data/X_reference.npy')
y = np.load('Data/y_reference.npy')



class_num=0
num_each=2000

In [3]:
print(X)
print(y.shape)
print(y[2000],y[1999],y[2001],y[1998])
print(y)

yhot=[]

conc=[0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7]



[[0.35522984 0.30701063 0.34318911 ... 0.25676307 0.14707421 0.24007765]
 [0.23345617 0.32298293 0.24379364 ... 0.14759503 0.19269395 0.23601629]
 [0.20275288 0.28382089 0.30361074 ... 0.0975013  0.15016    0.19614416]
 ...
 [0.38041554 0.30664527 0.4541858  ... 0.40751397 0.29672716 0.35193382]
 [0.38186143 0.25524518 0.20992925 ... 0.43850126 0.39891844 0.46098642]
 [0.37358719 0.29174137 0.32681815 ... 0.68908333 0.39855016 0.38085587]]
(60000,)
1.0 0.0 1.0 0.0
[ 0.  0.  0. ... 29. 29. 29.]


In [4]:
#data generation for 1 bacteria and 1 foreign
x_gen = []
y_lbl = []
for i in range(4):
    for cf in range(1,6):
    #with_foreign
        for j in range(i*2000, (i+1)*2000):
            foreign = np.random.randint(16000, 24000)
            cf=cf/10
            c1=1-cf
            cf=round(cf,2)
            c1=round(c1,2)
            if c1<=0:
                c1=0
            x = c1*X[j]+cf*X[foreign]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[4]=cf
            yhotenc=[0.0]*5
            yhotenc[i]=1.0
            yhotenc[4]=1.0
            yhot.append(yhotenc)
            y_lbl.append(yyy+[class_num])
        
    class_num+=1
    print(len(y_lbl))
    #without_foreign
    for j in range(i*2000, (i+1)*2000):
        x = X[j]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=1
        yhotenc=[0.0]*5
        yhotenc[i]=1.0
        yhot.append(yhotenc)
        y_lbl.append(yyy+[class_num])
    class_num+=1
    print(len(y_lbl))
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
print(yhot)
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for1_withforeign_class_validation_latest', yyc)
np.save('Data/X_datagen_for1_withforeign_validation_latest', xx)
np.save('Data/y_datagen_for1_withforeign_validation_latest', yy)

10000
12000
22000
24000
34000
36000
46000
48000
[[1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 

In [5]:
data1_1=np.load('Data/y_datagen_for1_withforeign_class_validation_latest.npy')
data1_2=np.load('Data/X_datagen_for1_withforeign_validation_latest.npy')

print(data1_1)

[0. 0. 0. ... 7. 7. 7.]


In [6]:
#data generation for 2 bacteria and 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []

for i in range(4):
    for j in range(i+1,4):
        #with_foreign
        for cf in range(1,6):
            cf=cf/10
            for _ in range(num_each):
                foreign = np.random.randint(16000,24000)
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                
                c1 = random.randint(0,int(10-cf*10+1))/10
                c2 = 1 - c1 -cf
                cf=round(cf,2)
                c1=round(c1,2)
                c2=round(c2,2)
                if c2<=0:
                    c2=0
                x = c1*X[first] + c2*X[second] +cf*X[foreign]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[4]=cf
                yhotenc=[0.0]*5
                yhotenc[i]=1.0
                yhotenc[j]=1.0
                yhotenc[4]=1.0
                yhot.append(yhotenc)
                y_lbl.append(yyy+[class_num])
        class_num+=1
        #without_foreign
        for _ in range(num_each):
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            c1 = random.randint(1,10)/10
            c2 = 1 - c1
            c1=round(c1,2)
            c2=round(c2,2)
            if c2<=0:
                c2=0
            x = c1*X[first] + c2*X[second]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            yhotenc=[0.0]*5
            yhotenc[i]=1.0
            yhotenc[j]=1.0
            yhot.append(yhotenc)
            y_lbl.append(yyy+[class_num])
        class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]
print(yy)
np.save('Data/y_datagen_for2_withforeign_class_validation_latest', yyc)
np.save('Data/X_datagen_for2_withforeign_validation_latest', xx)
np.save('Data/y_datagen_for2_withforeign_validation_latest', yy)

[[ 0.4  0.5  0.   0.   0.1  8. ]
 [ 0.4  0.5  0.   0.   0.1  8. ]
 [ 0.7  0.2  0.   0.   0.1  8. ]
 ...
 [ 0.   0.   0.3  0.7  0.  19. ]
 [ 0.   0.   0.6  0.4  0.  19. ]
 [ 0.   0.   0.1  0.9  0.  19. ]]


In [7]:
data2_1=np.load('Data/y_datagen_for2_withforeign_class_validation_latest.npy')
data2_2=np.load('Data/X_datagen_for2_withforeign_validation_latest.npy')


print(data2_1)

[ 8.  8.  8. ... 19. 19. 19.]


In [8]:
#data generation for 3 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            #with_foreign
            for cf in range(1,6):
                cf=cf/10
                for _ in range(num_each):
                    foreign = np.random.randint( 16000,24000)
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    c1=random.randint(0,int(10-cf*10))/10
                    c2=random.randint(0,int(10-c1*10-cf*10))/10
                    c3=1-c1-c2-cf
                    cf=round(cf,2)
                    c1=round(c1,2)
                    c2=round(c2,2)
                    c3=round(c3,2)
                    if c3<=0:
                        c3=0
                    x = c1*X[first] + c2*X[second] + c3*X[third]+cf*X[foreign]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[4]=cf
                    yhotenc=[0.0]*5
                    yhotenc[i]=1.0
                    yhotenc[j]=1.0
                    yhotenc[k]=1.0
                    yhotenc[4]=1.0
                    yhot.append(yhotenc)
                    y_lbl.append(yyy+[class_num])
            class_num+=1
            #without_foreign
            for _ in range(num_each):
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                c1=random.randint(1,10)/10
                c2=random.randint(0,int(10-c1*10))/10
                c3=1-c1-c2
                c1=round(c1,2)
                c2=round(c2,2)
                c3=round(c3,2)
                if c3<=0:
                    c3=0
                x = c1*X[first] + c2*X[second] + c3*X[third]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                yhotenc=[0.0]*5
                yhotenc[i]=1.0
                yhotenc[j]=1.0
                yhotenc[k]=1.0
                yhot.append(yhotenc)
                y_lbl.append(yyy+[class_num])
            class_num+=1

xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]

for i in yy:
    yyc+=[i[-1]]
print(yy)
np.save('Data/y_datagen_for3_withforeign_class_validation_latest', yyc)
np.save('Data/X_datagen_for3_withforeign_validation_latest', xx)
np.save('Data/y_datagen_for3_withforeign_validation_latest', yy)

[[ 0.2  0.2  0.5  0.   0.1 20. ]
 [ 0.3  0.5  0.1  0.   0.1 20. ]
 [ 0.   0.4  0.5  0.   0.1 20. ]
 ...
 [ 0.   0.9  0.   0.1  0.  27. ]
 [ 0.   0.7  0.2  0.1  0.  27. ]
 [ 0.   0.2  0.4  0.4  0.  27. ]]


In [9]:
data3_1=np.load('Data/y_datagen_for3_withforeign_class_validation_latest.npy')
data3_2=np.load('Data/X_datagen_for3_withforeign_validation_latest.npy')


print(data3_1)

[20. 20. 20. ... 27. 27. 27.]


In [10]:
#data generation for 4 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            for l in range(k+1,4):
                #with_foreign
                for cf in range(1,6):
                    cf=cf/10
                    for _ in range(num_each):
                        foreign = np.random.randint(16000,24000)
                        first = np.random.randint(i*2000, (i+1)*2000)
                        second = np.random.randint(j*2000, (j+1)*2000)
                        third = np.random.randint(k*2000,(k+1)*2000)
                        fourth = np.random.randint(l*2000,(l+1)*2000)
                        c1=random.randint(0,10-cf*10)/10
                        c2=random.randint(0,10-c1*10-cf*10)/10
                        c3=random.randint(0,10-c2*10-c1*10-cf*10)/10
                        c4=1-c1-c2-c3-cf
                        cf=round(cf,2)
                        c1=round(c1,2)
                        c2=round(c2,2)
                        c3=round(c3,2)
                        c4=round(c4,2)
                        if c4<=0:
                            c4=0
                        x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]+cf*X[foreign]
                        print(cf,c1,c2,c3,c4)
                        x_gen.append(x)
                        yyy=[0.0]*5
                        yyy[i]=c1
                        yyy[j]=c2
                        yyy[k]=c3
                        yyy[l]=c4
                        yyy[4]=cf
                        yhotenc=[0.0]*5
                        yhotenc[i]=1.0
                        yhotenc[j]=1.0
                        yhotenc[k]=1.0
                        yhotenc[l]=1.0
                        yhotenc[4]=1.0
                        yhot.append(yhotenc)
                        y_lbl.append(yyy+[class_num])
                class_num+=1
                #without_foreign
                for _ in range(num_each):
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    c1=random.randint(1,10)/10
                    c2=random.randint(0,10-c1*10)/10
                    c3=random.randint(0,10-c2*10-c1*10)/10
                    c4=1-c1-c2-c3
                    c1=round(c1,2)
                    c2=round(c2,2)
                    c3=round(c3,2)
                    c4=round(c4,2)
                    if c4<=0:
                        c4=0
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    yhotenc=[0.0]*5
                    yhotenc[i]=1.0
                    yhotenc[j]=1.0
                    yhotenc[k]=1.0
                    yhotenc[l]=1.0
                    yhot.append(yhotenc)
                    y_lbl.append(yyy+[class_num])
                class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]

np.save('Data/y_datagen_for4_withforeign_class_validation_latest', yyc)
np.save('Data/X_datagen_for4_withforeign_validation_latest', xx)
np.save('Data/y_datagen_for4_withforeign_validation_latest', yy)

0.1 0.0 0.1 0.4 0.4
0.1 0.7 0.0 0.0 0.2
0.1 0.5 0.1 0.2 0.1
0.1 0.2 0.1 0.1 0.5
0.1 0.9 0.0 0.0 0
0.1 0.3 0.2 0.1 0.3
0.1 0.0 0.5 0.4 0
0.1 0.8 0.0 0.1 0
0.1 0.2 0.0 0.1 0.6
0.1 0.6 0.1 0.0 0.2
0.1 0.3 0.3 0.3 0
0.1 0.3 0.5 0.0 0.1
0.1 0.1 0.0 0.0 0.8
0.1 0.5 0.4 0.0 0
0.1 0.9 0.0 0.0 0
0.1 0.5 0.0 0.1 0.3
0.1 0.5 0.0 0.3 0.1
0.1 0.4 0.0 0.5 0
0.1 0.7 0.1 0.1 0
0.1 0.0 0.5 0.1 0.3
0.1 0.6 0.1 0.2 0
0.1 0.3 0.5 0.0 0.1
0.1 0.8 0.0 0.1 0
0.1 0.8 0.0 0.0 0.1
0.1 0.6 0.1 0.0 0.2
0.1 0.4 0.1 0.0 0.4
0.1 0.8 0.0 0.0 0.1
0.1 0.0 0.0 0.2 0.7
0.1 0.4 0.1 0.1 0.3
0.1 0.5 0.3 0.1 0
0.1 0.9 0.0 0.0 0
0.1 0.1 0.2 0.5 0.1
0.1 0.9 0.0 0.0 0
0.1 0.7 0.2 0.0 0
0.1 0.1 0.8 0.0 0
0.1 0.7 0.0 0.2 0
0.1 0.1 0.0 0.8 0
0.1 0.1 0.0 0.3 0.5
0.1 0.5 0.2 0.2 0
0.1 0.7 0.2 0.0 0
0.1 0.9 0.0 0.0 0
0.1 0.8 0.0 0.0 0.1
0.1 0.6 0.3 0.0 0
0.1 0.7 0.2 0.0 0
0.1 0.1 0.7 0.0 0.1
0.1 0.0 0.5 0.1 0.3
0.1 0.3 0.1 0.2 0.3
0.1 0.0 0.2 0.3 0.4
0.1 0.5 0.1 0.1 0.2
0.1 0.3 0.5 0.0 0.1
0.1 0.6 0.1 0.2 0
0.1 0.0 0.7 0.0 0.2
0.1 0.

0.2 0.1 0.7 0.0 0
0.2 0.4 0.0 0.2 0.2
0.2 0.5 0.2 0.1 0
0.2 0.8 0.0 0.0 0
0.2 0.0 0.4 0.1 0.3
0.2 0.6 0.2 0.0 0
0.2 0.6 0.2 0.0 0
0.2 0.8 0.0 0.0 0
0.2 0.0 0.3 0.5 0
0.2 0.1 0.3 0.2 0.2
0.2 0.1 0.3 0.1 0.3
0.2 0.4 0.3 0.1 0
0.2 0.3 0.2 0.0 0.3
0.2 0.8 0.0 0.0 0
0.2 0.3 0.5 0.0 0
0.2 0.2 0.6 0.0 0
0.2 0.7 0.1 0.0 0
0.2 0.1 0.2 0.2 0.3
0.2 0.0 0.2 0.5 0.1
0.2 0.6 0.0 0.2 0
0.2 0.4 0.2 0.2 0
0.2 0.6 0.1 0.1 0
0.2 0.1 0.3 0.4 0
0.2 0.6 0.2 0.0 0
0.2 0.0 0.5 0.0 0.3
0.2 0.2 0.0 0.2 0.4
0.2 0.3 0.0 0.4 0.1
0.2 0.0 0.4 0.0 0.4
0.2 0.1 0.0 0.4 0.3
0.2 0.3 0.3 0.0 0.2
0.2 0.4 0.0 0.3 0.1
0.2 0.0 0.3 0.1 0.4
0.2 0.0 0.7 0.1 0
0.2 0.0 0.7 0.0 0.1
0.2 0.1 0.6 0.1 0
0.2 0.0 0.1 0.4 0.3
0.2 0.8 0.0 0.0 0
0.2 0.6 0.0 0.0 0.2
0.2 0.5 0.3 0.0 0
0.2 0.7 0.0 0.1 0
0.2 0.7 0.0 0.0 0.1
0.2 0.4 0.0 0.3 0.1
0.2 0.7 0.0 0.0 0.1
0.2 0.1 0.5 0.2 0
0.2 0.2 0.3 0.0 0.3
0.2 0.0 0.8 0.0 0
0.2 0.0 0.0 0.2 0.6
0.2 0.6 0.0 0.0 0.2
0.2 0.7 0.1 0.0 0
0.2 0.3 0.1 0.0 0.4
0.2 0.8 0.0 0.0 0
0.2 0.4 0.1 0.3 0
0.2 0.6 0.2 0.

0.2 0.5 0.1 0.2 0
0.2 0.3 0.1 0.1 0.3
0.2 0.0 0.0 0.8 0
0.2 0.5 0.0 0.2 0.1
0.2 0.8 0.0 0.0 0
0.2 0.3 0.5 0.0 0
0.2 0.2 0.3 0.0 0.3
0.2 0.0 0.5 0.0 0.3
0.2 0.3 0.2 0.2 0.1
0.2 0.5 0.1 0.2 0
0.2 0.8 0.0 0.0 0
0.2 0.4 0.4 0.0 0
0.2 0.0 0.0 0.2 0.6
0.2 0.5 0.1 0.0 0.2
0.2 0.4 0.2 0.2 0
0.2 0.3 0.5 0.0 0
0.2 0.3 0.1 0.0 0.4
0.2 0.5 0.0 0.3 0
0.2 0.4 0.1 0.2 0.1
0.2 0.4 0.4 0.0 0
0.2 0.8 0.0 0.0 0
0.2 0.2 0.6 0.0 0
0.2 0.1 0.7 0.0 0
0.2 0.7 0.1 0.0 0
0.2 0.7 0.0 0.1 0
0.2 0.2 0.5 0.0 0.1
0.2 0.6 0.2 0.0 0
0.2 0.8 0.0 0.0 0
0.2 0.7 0.1 0.0 0
0.2 0.4 0.0 0.1 0.3
0.2 0.2 0.5 0.0 0.1
0.2 0.1 0.7 0.0 0
0.2 0.5 0.0 0.1 0.2
0.2 0.7 0.1 0.0 0
0.2 0.7 0.0 0.1 0
0.2 0.4 0.0 0.2 0.2
0.2 0.2 0.3 0.1 0.2
0.2 0.5 0.0 0.0 0.3
0.2 0.0 0.0 0.6 0.2
0.2 0.2 0.3 0.3 0
0.2 0.8 0.0 0.0 0
0.2 0.3 0.0 0.0 0.5
0.2 0.0 0.6 0.1 0.1
0.2 0.0 0.4 0.0 0.4
0.2 0.6 0.0 0.0 0.2
0.2 0.3 0.5 0.0 0
0.2 0.3 0.2 0.1 0.2
0.2 0.7 0.0 0.1 0
0.2 0.8 0.0 0.0 0
0.2 0.5 0.2 0.0 0.1
0.2 0.8 0.0 0.0 0
0.2 0.0 0.5 0.1 0.2
0.2 0.3 0.3 0.1 

0.3 0.7 0.0 0.0 0
0.3 0.7 0.0 0.0 0
0.3 0.3 0.3 0.0 0.1
0.3 0.3 0.3 0.0 0.1
0.3 0.4 0.2 0.1 0
0.3 0.4 0.0 0.1 0.2
0.3 0.7 0.0 0.0 0
0.3 0.3 0.1 0.1 0.2
0.3 0.7 0.0 0.0 0
0.3 0.2 0.4 0.1 0
0.3 0.2 0.1 0.0 0.4
0.3 0.2 0.2 0.1 0.2
0.3 0.1 0.3 0.3 0
0.3 0.1 0.2 0.1 0.3
0.3 0.2 0.2 0.1 0.2
0.3 0.0 0.5 0.1 0.1
0.3 0.6 0.0 0.0 0.1
0.3 0.0 0.4 0.3 0
0.3 0.4 0.3 0.0 0
0.3 0.5 0.1 0.1 0
0.3 0.0 0.2 0.5 0
0.3 0.2 0.3 0.0 0.2
0.3 0.7 0.0 0.0 0
0.3 0.0 0.3 0.3 0.1
0.3 0.6 0.1 0.0 0
0.3 0.3 0.4 0.0 0
0.3 0.0 0.1 0.3 0.3
0.3 0.7 0.0 0.0 0
0.3 0.1 0.0 0.0 0.6
0.3 0.7 0.0 0.0 0
0.3 0.0 0.3 0.3 0.1
0.3 0.6 0.1 0.0 0
0.3 0.2 0.3 0.1 0.1
0.3 0.0 0.3 0.1 0.3
0.3 0.3 0.0 0.4 0
0.3 0.0 0.0 0.0 0.7
0.3 0.5 0.2 0.0 0
0.3 0.5 0.0 0.0 0.2
0.3 0.3 0.1 0.1 0.2
0.3 0.3 0.1 0.0 0.3
0.3 0.4 0.0 0.3 0
0.3 0.4 0.3 0.0 0
0.3 0.6 0.1 0.0 0
0.3 0.5 0.2 0.0 0
0.3 0.2 0.0 0.2 0.3
0.3 0.6 0.1 0.0 0
0.3 0.7 0.0 0.0 0
0.3 0.7 0.0 0.0 0
0.3 0.2 0.5 0.0 0
0.3 0.1 0.3 0.1 0.2
0.3 0.3 0.1 0.3 0
0.3 0.0 0.5 0.1 0.1
0.3 0.2 0.1 0.4 

0.4 0.3 0.2 0.0 0.1
0.4 0.0 0.3 0.0 0.3
0.4 0.6 0.0 0.0 0
0.4 0.5 0.1 0.0 0
0.4 0.0 0.3 0.0 0.3
0.4 0.2 0.2 0.1 0.1
0.4 0.3 0.0 0.2 0.1
0.4 0.4 0.0 0.0 0.2
0.4 0.3 0.2 0.0 0.1
0.4 0.1 0.5 0.0 0
0.4 0.5 0.1 0.0 0
0.4 0.0 0.4 0.2 0
0.4 0.6 0.0 0.0 0
0.4 0.5 0.0 0.1 0
0.4 0.1 0.2 0.2 0.1
0.4 0.1 0.3 0.2 0
0.4 0.0 0.0 0.1 0.5
0.4 0.2 0.3 0.1 0
0.4 0.3 0.2 0.0 0.1
0.4 0.3 0.3 0.0 0
0.4 0.2 0.0 0.2 0.2
0.4 0.2 0.0 0.2 0.2
0.4 0.4 0.1 0.0 0.1
0.4 0.2 0.0 0.1 0.3
0.4 0.5 0.1 0.0 0
0.4 0.3 0.0 0.0 0.3
0.4 0.3 0.3 0.0 0
0.4 0.0 0.6 0.0 0
0.4 0.2 0.1 0.1 0.2
0.4 0.5 0.0 0.0 0.1
0.4 0.0 0.5 0.0 0.1
0.4 0.5 0.0 0.0 0.1
0.4 0.5 0.0 0.0 0.1
0.4 0.6 0.0 0.0 0
0.4 0.1 0.0 0.0 0.5
0.4 0.0 0.4 0.0 0.2
0.4 0.5 0.0 0.0 0.1
0.4 0.2 0.3 0.0 0.1
0.4 0.4 0.0 0.2 0
0.4 0.6 0.0 0.0 0
0.4 0.1 0.3 0.0 0.2
0.4 0.6 0.0 0.0 0
0.4 0.0 0.0 0.0 0.6
0.4 0.5 0.1 0.0 0
0.4 0.3 0.0 0.1 0.2
0.4 0.4 0.1 0.1 0
0.4 0.0 0.6 0.0 0
0.4 0.5 0.1 0.0 0
0.4 0.4 0.2 0.0 0
0.4 0.4 0.2 0.0 0
0.4 0.4 0.1 0.0 0.1
0.4 0.3 0.0 0.2 0.1
0.4 0.

0.5 0.2 0.3 0.0 0
0.5 0.3 0.0 0.1 0.1
0.5 0.0 0.2 0.2 0.1
0.5 0.1 0.1 0.0 0.3
0.5 0.2 0.0 0.0 0.3
0.5 0.0 0.4 0.1 0
0.5 0.5 0.0 0.0 0
0.5 0.3 0.1 0.0 0.1
0.5 0.4 0.1 0.0 0
0.5 0.0 0.5 0.0 0
0.5 0.4 0.1 0.0 0
0.5 0.5 0.0 0.0 0
0.5 0.0 0.5 0.0 0
0.5 0.1 0.3 0.0 0.1
0.5 0.1 0.2 0.2 0
0.5 0.4 0.0 0.1 0
0.5 0.4 0.0 0.0 0.1
0.5 0.0 0.2 0.1 0.2
0.5 0.0 0.1 0.1 0.3
0.5 0.4 0.0 0.1 0
0.5 0.3 0.1 0.1 0
0.5 0.4 0.1 0.0 0
0.5 0.5 0.0 0.0 0
0.5 0.3 0.2 0.0 0
0.5 0.4 0.1 0.0 0
0.5 0.2 0.1 0.1 0.1
0.5 0.2 0.0 0.2 0.1
0.5 0.1 0.3 0.1 0
0.5 0.2 0.2 0.1 0
0.5 0.1 0.4 0.0 0
0.5 0.5 0.0 0.0 0
0.5 0.3 0.2 0.0 0
0.5 0.5 0.0 0.0 0
0.5 0.4 0.0 0.1 0
0.5 0.0 0.5 0.0 0
0.5 0.2 0.2 0.1 0
0.5 0.5 0.0 0.0 0
0.5 0.5 0.0 0.0 0
0.5 0.4 0.1 0.0 0
0.5 0.5 0.0 0.0 0
0.5 0.1 0.4 0.0 0
0.5 0.2 0.2 0.0 0.1
0.5 0.3 0.2 0.0 0
0.5 0.4 0.0 0.1 0
0.5 0.2 0.1 0.2 0
0.5 0.0 0.1 0.1 0.3
0.5 0.2 0.2 0.0 0.1
0.5 0.0 0.2 0.0 0.3
0.5 0.1 0.1 0.1 0.2
0.5 0.5 0.0 0.0 0
0.5 0.2 0.2 0.0 0.1
0.5 0.5 0.0 0.0 0
0.5 0.0 0.0 0.2 0.3
0.5 0.2 0.

In [11]:
print(yy)

[[ 0.   0.1  0.4  0.4  0.1 28. ]
 [ 0.7  0.   0.   0.2  0.1 28. ]
 [ 0.5  0.1  0.2  0.1  0.1 28. ]
 ...
 [ 0.3  0.6  0.   0.1  0.  29. ]
 [ 0.2  0.   0.   0.8  0.  29. ]
 [ 0.5  0.4  0.1  0.   0.  29. ]]


In [12]:
data4_1=np.load('Data/y_datagen_for4_withforeign_class_validation_latest.npy')
data4_2=np.load('Data/X_datagen_for4_withforeign_validation_latest.npy')


print(data4_1)

[28. 28. 28. ... 29. 29. 29.]


In [13]:
XXfinalclass=np.vstack((data1_2,data2_2, data3_2,data4_2))
yyfinalclass = np.hstack((data1_1,data2_1, data3_1,data4_1))
print(XXfinalclass)
print(yyfinalclass)


np.save('Data/X_datagen_allcomb_foreign_class_fixed_more_latest_validation', XXfinalclass)
np.save('Data/y_datagen_allcomb_foreign_class_fixed_more_latest_validation', yyfinalclass)



[[0.33899521 0.3049215  0.33808189 ... 0.2533314  0.17099366 0.23618373]
 [0.23418154 0.32344297 0.2456755  ... 0.14857899 0.19563286 0.23817754]
 [0.20275288 0.28382089 0.30361074 ... 0.0975013  0.15016    0.19614416]
 ...
 [0.17064238 0.19137788 0.18696712 ... 0.18713724 0.15363587 0.20423999]
 [0.35105004 0.49682224 0.53347803 ... 0.3274     0.52137905 0.32961262]
 [0.20322671 0.19895572 0.27045755 ... 0.16518018 0.19990419 0.18970078]]
[ 0.  0.  0. ... 29. 29. 29.]


In [4]:
# print(yhot)
# np.save("Data/y_datagen_allcomb_foreign_hotencoding_fixed_more_latest_validation",yhot)

z=np.load("Data/y_datagen_allcomb_foreign_hotencoding_fixed_more_latest_validation.npy")
print(z.shape)
print(z)

(180000, 5)
[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 ...
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 0.]]


In [17]:
XXX=np.load("Data/X_datagen_allcomb_foreign_class_fixed_more_latest_validation.npy")

np.random.shuffle(XXX)
np.save('Data/vali_creation.npy', XXX)
XXX.shape

(180000, 1000)

In [18]:
pp=np.load('Data/vali_creation.npy',allow_pickle=True)

In [19]:
pp.shape

(180000, 1000)