In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [2]:
X = np.load('Data/X_reference.npy')
y = np.load('Data/y_reference.npy')
class_num=0
num_each=2000

In [3]:
print(X)
print(y.shape)
print(y[2000],y[1999],y[2001],y[1998])
print(y)

yhot=[]

conc=[0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7]



[[0.35522984 0.30701063 0.34318911 ... 0.25676307 0.14707421 0.24007765]
 [0.23345617 0.32298293 0.24379364 ... 0.14759503 0.19269395 0.23601629]
 [0.20275288 0.28382089 0.30361074 ... 0.0975013  0.15016    0.19614416]
 ...
 [0.38041554 0.30664527 0.4541858  ... 0.40751397 0.29672716 0.35193382]
 [0.38186143 0.25524518 0.20992925 ... 0.43850126 0.39891844 0.46098642]
 [0.37358719 0.29174137 0.32681815 ... 0.68908333 0.39855016 0.38085587]]
(60000,)
1.0 0.0 1.0 0.0
[ 0.  0.  0. ... 29. 29. 29.]


In [4]:
#data generation for 1 bacteria and 1 foreign
x_gen = []
y_lbl = []
for i in range(4):
    #with_foreign
    for j in range(i*2000, (i+1)*2000):
        foreign = np.random.randint(8000, 16000)
        cf=random.randint(0,10)/10
        c1=1-cf
        x = c1*X[j]+cf*X[foreign]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=c1
        yyy[4]=cf
        yhotenc=[0.0]*5
        yhotenc[i]=1.0
        yhotenc[4]=1.0
        yhot.append(yhotenc)
        y_lbl.append(yyy+[class_num])
        
    class_num+=1
    #without_foreign
    for j in range(i*2000, (i+1)*2000):
        x = X[j]
        x_gen.append(x)
        yyy=[0.0]*5
        yyy[i]=1
        yhotenc=[0.0]*5
        yhotenc[i]=1.0
        yhot.append(yhotenc)
        y_lbl.append(yyy+[class_num])
    class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
print(yhot)
for i in yy:
    yyc+=[i[-1]]
np.save('Data/y_datagen_for1_withforeign_class_fixed', yyc)
np.save('Data/X_datagen_for1_withforeign_fixed', xx)
np.save('Data/y_datagen_for1_withforeign_fixed', yy)

[[1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], 

In [5]:
data1_1=np.load('Data/y_datagen_for1_withforeign_class_fixed.npy')
data1_2=np.load('Data/X_datagen_for1_withforeign_fixed.npy')

print(data1_1)

[0. 0. 0. ... 7. 7. 7.]


In [6]:
#data generation for 2 bacteria and 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        #with_foreign
        for _ in range(num_each):
            foreign = np.random.randint(8000, 16000)
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            cf=random.randint(1,10)/10
            c1 = random.randint(0,int(10-cf*10+1))/10
            c2 = 1 - c1 -cf
            x = c1*X[first] + c2*X[second] +cf*X[foreign]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            yyy[4]=cf
            yhotenc=[0.0]*5
            yhotenc[i]=1.0
            yhotenc[j]=1.0
            yhotenc[4]=1.0
            yhot.append(yhotenc)
            y_lbl.append(yyy+[class_num])
        class_num+=1
        #without_foreign
        for _ in range(num_each):
            first = np.random.randint(i*2000, (i+1)*2000)
            second = np.random.randint(j*2000, (j+1)*2000)
            c1 = random.randint(1,10)/10
            c2 = 1 - c1
            x = c1*X[first] + c2*X[second]
            x_gen.append(x)
            yyy=[0.0]*5
            yyy[i]=c1
            yyy[j]=c2
            yhotenc=[0.0]*5
            yhotenc[i]=1.0
            yhotenc[j]=1.0
            yhot.append(yhotenc)
            y_lbl.append(yyy+[class_num])
        class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]
print(yy)
np.save('Data/y_datagen_for2_withforeign_class_fixed', yyc)
np.save('Data/X_datagen_for2_withforeign_fixed', xx)
np.save('Data/y_datagen_for2_withforeign_fixed', yy)

[[ 0.   0.8  0.   0.   0.2  8. ]
 [ 0.   0.1  0.   0.   0.9  8. ]
 [ 0.1  0.4  0.   0.   0.5  8. ]
 ...
 [ 0.   0.   0.5  0.5  0.  19. ]
 [ 0.   0.   0.7  0.3  0.  19. ]
 [ 0.   0.   0.3  0.7  0.  19. ]]


In [7]:
data2_1=np.load("Data/y_datagen_for2_withforeign_class_fixed.npy")
data2_2=np.load('Data/X_datagen_for2_withforeign_fixed.npy')

print(data2_1)

[ 8.  8.  8. ... 19. 19. 19.]


In [8]:
#data generation for 3 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            #with_foreign
            for _ in range(num_each):
                foreign = np.random.randint(8000, 16000)
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                cf=random.randint(1,10)/10
                c1=random.randint(0,int(10-cf*10))/10
                c2=random.randint(0,int(10-c1*10-cf*10))/10
                c3=1-c1-c2-cf
                x = c1*X[first] + c2*X[second] + c3*X[third]+cf*X[foreign]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                yyy[4]=cf
                yhotenc=[0.0]*5
                yhotenc[i]=1.0
                yhotenc[j]=1.0
                yhotenc[k]=1.0
                yhotenc[4]=1.0
                yhot.append(yhotenc)
                y_lbl.append(yyy+[class_num])
            class_num+=1
            #without_foreign
            for _ in range(num_each):
                first = np.random.randint(i*2000, (i+1)*2000)
                second = np.random.randint(j*2000, (j+1)*2000)
                third = np.random.randint(k*2000,(k+1)*2000)
                c1=random.randint(1,10)/10
                c2=random.randint(0,int(10-c1*10))/10
                c3=1-c1-c2
                x = c1*X[first] + c2*X[second] + c3*X[third]
                x_gen.append(x)
                yyy=[0.0]*5
                yyy[i]=c1
                yyy[j]=c2
                yyy[k]=c3
                yhotenc=[0.0]*5
                yhotenc[i]=1.0
                yhotenc[j]=1.0
                yhotenc[k]=1.0
                yhot.append(yhotenc)
                y_lbl.append(yyy+[class_num])
            class_num+=1

xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]

for i in yy:
    yyc+=[i[-1]]
print(yy)
np.save('Data/y_datagen_for3_withforeign_class_fixed', yyc)
np.save('Data/X_datagen_for3_withforeign_fixed', xx)
np.save('Data/y_datagen_for3_withforeign_fixed', yy)

[[ 0.   0.1  0.   0.   0.9 20. ]
 [ 0.   0.   0.   0.   1.  20. ]
 [ 0.   0.6  0.3  0.   0.1 20. ]
 ...
 [ 0.   0.1  0.1  0.8  0.  27. ]
 [ 0.   0.7  0.1  0.2  0.  27. ]
 [ 0.   0.1  0.7  0.2  0.  27. ]]


In [9]:
data3_1=np.load("Data/y_datagen_for3_withforeign_class_fixed.npy")
data3_2=np.load('Data/X_datagen_for3_withforeign_fixed.npy')

print(data3_1)

[20. 20. 20. ... 27. 27. 27.]


In [10]:
#data generation for 4 bacteria with 1 foreign


from itertools import permutations
l = list(permutations(range(0, 4)))

x_gen = []
y_lbl = []
for i in range(4):
    for j in range(i+1,4):
        for k in range(j+1,4):
            for l in range(k+1,4):
                #with_foreign
                for _ in range(num_each):
                    foreign = np.random.randint(8000, 16000)
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    cf=random.randint(1,10)/10
                    c1=random.randint(0,10-cf*10)/10
                    c2=random.randint(0,10-c1*10-cf*10)/10
                    c3=random.randint(0,10-c2*10-c1*10-cf*10)/10
                    c4=1-c1-c2-c3-cf
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]+cf*X[foreign]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    yyy[4]=cf
                    yhotenc=[0.0]*5
                    yhotenc[i]=1.0
                    yhotenc[j]=1.0
                    yhotenc[k]=1.0
                    yhotenc[l]=1.0
                    yhotenc[4]=1.0
                    yhot.append(yhotenc)
                    y_lbl.append(yyy+[class_num])
                class_num+=1
                #without_foreign
                for _ in range(num_each):
                    first = np.random.randint(i*2000, (i+1)*2000)
                    second = np.random.randint(j*2000, (j+1)*2000)
                    third = np.random.randint(k*2000,(k+1)*2000)
                    fourth = np.random.randint(l*2000,(l+1)*2000)
                    c1=random.randint(1,10)/10
                    c2=random.randint(0,10-c1*10)/10
                    c3=random.randint(0,10-c2*10-c1*10)/10
                    c4=1-c1-c2-c3
                    x = c1*X[first] + c2*X[second] + c3*X[third]+ c4*X[fourth]
                    x_gen.append(x)
                    yyy=[0.0]*5
                    yyy[i]=c1
                    yyy[j]=c2
                    yyy[k]=c3
                    yyy[l]=c4
                    yhotenc=[0.0]*5
                    yhotenc[i]=1.0
                    yhotenc[j]=1.0
                    yhotenc[k]=1.0
                    yhotenc[l]=1.0
                    yhot.append(yhotenc)
                    y_lbl.append(yyy+[class_num])
                class_num+=1
xx = np.array(x_gen)
yy = np.array(y_lbl)
yyc=[]
for i in yy:
    yyc+=[i[-1]]

np.save('Data/y_datagen_for4_withforeign_class_fixed', yyc)
np.save('Data/X_datagen_for4_withforeign_fixed', xx)
np.save('Data/y_datagen_for4_withforeign_fixed', yy)

In [14]:
print(yy)

[[ 1.00000000e-01  1.00000000e-01  0.00000000e+00  0.00000000e+00
   8.00000000e-01  2.80000000e+01]
 [ 1.00000000e-01  8.00000000e-01  0.00000000e+00 -2.77555756e-17
   1.00000000e-01  2.80000000e+01]
 [ 1.00000000e-01  1.00000000e-01  5.00000000e-01  5.55111512e-17
   3.00000000e-01  2.80000000e+01]
 ...
 [ 7.00000000e-01  3.00000000e-01  0.00000000e+00  5.55111512e-17
   0.00000000e+00  2.90000000e+01]
 [ 5.00000000e-01  2.00000000e-01  2.00000000e-01  1.00000000e-01
   0.00000000e+00  2.90000000e+01]
 [ 3.00000000e-01  4.00000000e-01  1.00000000e-01  2.00000000e-01
   0.00000000e+00  2.90000000e+01]]


In [11]:
data4_1=np.load('Data/y_datagen_for4_withforeign_class_fixed.npy')
data4_2=np.load('Data/X_datagen_for4_withforeign_fixed.npy')

print(data4_1)

[28. 28. 28. ... 29. 29. 29.]


In [12]:
XXfinalclass=np.vstack((data1_2,data2_2, data3_2,data4_2))
yyfinalclass = np.hstack((data1_1,data2_1, data3_1,data4_1))
print(XXfinalclass)
print(yyfinalclass)

np.save('Data/X_datagen_allcomb_foreign_class_fixed', XXfinalclass)
np.save('Data/y_datagen_allcomb_foreign_class_fixed', yyfinalclass)


[[0.37499815 0.27226839 0.36484623 ... 0.32120719 0.28055232 0.35180713]
 [0.25533914 0.31764865 0.24819448 ... 0.17609843 0.21449642 0.27360746]
 [0.39432336 0.33516768 0.34864857 ... 0.27609001 0.50060099 0.59838054]
 ...
 [0.21694987 0.17255015 0.31822772 ... 0.38831406 0.33041412 0.36726909]
 [0.33957495 0.28654884 0.32171963 ... 0.32476306 0.25121298 0.26971744]
 [0.27513314 0.31291381 0.28967447 ... 0.32153982 0.36455181 0.32481424]]
[ 0.  0.  0. ... 29. 29. 29.]


In [13]:
print(yhot)
np.save("Data/y_datagen_allcomb_foreign_hotencoding_fixed",yhot)

z=np.load("Data/y_datagen_allcomb_foreign_hotencoding_fixed.npy")
print(z.shape)
print(z)

[[1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], [1.0, 0.0, 0.0, 0.0, 1.0], 