In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow import keras
from sklearn.metrics import accuracy_score
import tensorflow as tf

In [2]:
X = np.load('Data/X_datagen_allcomb_foreign_class_fixed_more_latest_validation.npy')
y = np.load('Data/y_datagen_allcomb_foreign_hotencoding_fixed_more_latest_validation.npy')

In [3]:
print(X.shape)
print(y.shape)

(180000, 1000)
(180000, 5)


In [4]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,shuffle=True, test_size=0.2, random_state=42)


print(X_train[:10])
print(y_train[:10])

[[0.25119375 0.37721175 0.41184635 ... 0.33290825 0.46742664 0.2065948 ]
 [0.1305774  0.2217086  0.21456133 ... 0.33408223 0.37867895 0.35890811]
 [0.26566216 0.27685149 0.25693659 ... 0.21393631 0.27717197 0.27121359]
 ...
 [0.32521211 0.26377401 0.35339066 ... 0.46889027 0.36751316 0.46010555]
 [0.2792028  0.24759356 0.33096443 ... 0.4248202  0.29770028 0.3450426 ]
 [0.24225477 0.21701619 0.25226966 ... 0.42403007 0.27779614 0.3545274 ]]
[[1. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 1.]]


# Predicting for first column pure bacteria


In [5]:
from keras.models import load_model

In [6]:
filepath = './Models_individual/model1.h5'
model = load_model(filepath)

In [7]:
y_tr = model.predict(X_train)
y_ts = model.predict(X_test)

In [8]:
y_tr = np.where(y_tr.reshape(-1) <0.5, 0,1)
y_ts = np.where(y_ts.reshape(-1) <0.5, 0,1)

In [9]:
tr1 = accuracy_score(y_train[:,0],y_tr)
ts1 = accuracy_score(y_test[:,0],y_ts)
print("train accuracy:",tr1)
print("test accuracy:",ts1)

train accuracy: 0.9035416666666667
test accuracy: 0.9036666666666666


# Predicting for second column pure bacteria

In [10]:
filepath = './Models_individual/model2.h5'
model = tf.keras.models.load_model(filepath)

In [11]:
y_tr = model.predict(X_train)
y_ts = model.predict(X_test)

In [12]:
y_tr = np.where(y_tr.reshape(-1) <0.5, 0,1)
y_ts = np.where(y_ts.reshape(-1) <0.5, 0,1)

In [13]:
tr2 = accuracy_score(y_train[:,1],y_tr)
ts2 = accuracy_score(y_test[:,1],y_ts)
print("train accuracy:",tr2)
print("test accuracy:",ts2)

train accuracy: 0.8764375
test accuracy: 0.8794166666666666


# Predicting for third column pure bacteria

In [14]:
filepath = './Models_individual/model3.h5'
model = load_model(filepath)
y_tr = model.predict(X_train)
y_ts = model.predict(X_test)
y_tr = np.where(y_tr.reshape(-1) <0.5, 0,1)
y_ts = np.where(y_ts.reshape(-1) <0.5, 0,1)
tr3 = accuracy_score(y_train[:,2],y_tr)
ts3 = accuracy_score(y_test[:,2],y_ts)
print("train accuracy:",tr3)
print("test accuracy:",ts3)

train accuracy: 0.7583402777777778
test accuracy: 0.7569166666666667


# Predicting for fourth column bacteria

In [16]:
filepath = './Models_individual/model4.h5'
model = load_model(filepath)
y_tr = model.predict(X_train)
y_ts = model.predict(X_test)
y_tr = np.where(y_tr.reshape(-1) <0.5, 0,1)
y_ts = np.where(y_ts.reshape(-1) <0.5, 0,1)
tr4 = accuracy_score(y_train[:,3],y_tr)
ts4 = accuracy_score(y_test[:,3],y_ts)
print("train accuracy:",tr4)
print("test accuracy:",ts4)

train accuracy: 0.759875
test accuracy: 0.75975
